/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package br.com.verificasms;
import br.com.verificasms.model.Usuario;
import javax.swing.JFrame;
/**
 *
 * @author gabri
 */
public class ComprovantePanel extends javax.swing.JPanel {
    private Usuario remetente;
    private Usuario destinatario;
    private JFrame frame;

    public ComprovantePanel(JFrame frame, Usuario remetente, Usuario destinatario) {
        this.frame = frame;
        this.remetente = remetente;
        this.destinatario = destinatario;
        initComponents();
       

        remetenteLabel.setText(remetente.getNome());
        destinatarioLabel.setText(destinatario.getNome());
    }

    private void btnSairActionPerformed(java.awt.event.ActionEvent evt) {
        System.exit(0);
    }

    private void btnDenunciaActionPerformed(java.awt.event.ActionEvent evt) {
        frame.setContentPane(new DenunciaPanel(frame, destinatario));
        frame.revalidate();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        remetenteLabel = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        destinatarioLabel = new javax.swing.JLabel();
        denunciarBtn = new javax.swing.JButton();
        sairBtn = new javax.swing.JButton();

        remetenteLabel.setText("jLabel1");

        jLabel1.setText("Valor enviado de:");

        jLabel2.setText("Para:");

        destinatarioLabel.setText("jLabel3");

        denunciarBtn.setText("Denunciar");
        denunciarBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                denunciarBtnActionPerformed(evt);
            }
        });

        sairBtn.setText("Sair");
        sairBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sairBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(destinatarioLabel)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1)
                            .addComponent(remetenteLabel))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(denunciarBtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 160, Short.MAX_VALUE)
                        .addComponent(sairBtn)
                        .addGap(38, 38, 38))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(remetenteLabel)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(destinatarioLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 184, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(denunciarBtn)
                    .addComponent(sairBtn))
                .addGap(123, 123, 123))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void sairBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sairBtnActionPerformed
          System.exit(0);
    }//GEN-LAST:event_sairBtnActionPerformed

    private void denunciarBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_denunciarBtnActionPerformed
        frame.setContentPane(new DenunciaPanel(frame, destinatario));
        frame.revalidate();
        frame.repaint();
    }//GEN-LAST:event_denunciarBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton denunciarBtn;
    private javax.swing.JLabel destinatarioLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel remetenteLabel;
    private javax.swing.JButton sairBtn;
    // End of variables declaration//GEN-END:variables
}
