/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package br.com.verificasms;
import Dto.FlagResponseDTO;
import com.fasterxml.jackson.databind.ObjectMapper;

import javax.swing.*;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;
import java.io.BufferedReader;
import java.io.InputStreamReader;
import java.net.HttpURLConnection;
import java.net.URL;
import java.net.URLEncoder;
import java.util.stream.Collectors;

/**
 *
 * @author gabri
 */
public class FlagPanel extends javax.swing.JPanel {
    private DefaultListModel<String> listaModel = new DefaultListModel<>();
    private final ObjectMapper mapper = new ObjectMapper();

    /**
     * Creates new form FlagPanel
     */
    public FlagPanel() {
        initComponents();
        configurarEventos();
        listaResultados.setModel(listaModel);
    }

    private void configurarEventos() {
    txtBuscarMotivo.getDocument().addDocumentListener(new DocumentListener() {
        public void insertUpdate(DocumentEvent e) { buscarPorMotivo(); }
        public void removeUpdate(DocumentEvent e) { buscarPorMotivo(); }
        public void changedUpdate(DocumentEvent e) { buscarPorMotivo(); }
    });

    txtBuscarId.addActionListener(e -> buscarPorId(txtBuscarId.getText().trim()));
}
    
    private void buscarPorMotivo() {
    String motivo = txtBuscarMotivo.getText().trim();
    if (motivo.isEmpty()) {
        listaModel.clear();
        return;
    }

    new Thread(() -> {
        try {
            String encoded = URLEncoder.encode(motivo, "UTF-8");
            URL url = new URL("http://localhost:8080/flags/busca?=" + encoded);
            HttpURLConnection con = (HttpURLConnection) url.openConnection();
            con.setRequestMethod("GET");

            BufferedReader in = new BufferedReader(new InputStreamReader(con.getInputStream()));
            String response = in.lines().collect(Collectors.joining());
            in.close();

            FlagResponseDTO[] flags = mapper.readValue(response, FlagResponseDTO[].class);

            SwingUtilities.invokeLater(() -> {
                listaModel.clear();
                for (FlagResponseDTO flag : flags) {
                    listaModel.addElement(flag.getId() + " - " + flag.getMotivo());
                }
            });

        } catch (Exception e) {
            e.printStackTrace();
        }
    }).start();
}
    
    private void buscarPorId(String idStr) {
    try {
        Long id = Long.parseLong(idStr);

        new Thread(() -> {
            try {
                URL url = new URL("http://localhost:8080/flags/buscaid?id=" + id);
                HttpURLConnection con = (HttpURLConnection) url.openConnection();
                con.setRequestMethod("GET");

                BufferedReader in = new BufferedReader(new InputStreamReader(con.getInputStream()));
                String response = in.lines().collect(Collectors.joining());
                in.close();

                FlagResponseDTO[] flags = mapper.readValue(response, FlagResponseDTO[].class);

                SwingUtilities.invokeLater(() -> {
                    listaModel.clear();
                    for (FlagResponseDTO flag : flags) {
                        listaModel.addElement(flag.getId() + " - " + flag.getMotivo());
                    }
                });

            } catch (Exception e) {
                e.printStackTrace();
            }
        }).start();

    } catch (NumberFormatException e) {
        JOptionPane.showMessageDialog(this, "ID inválido.");
    }
}


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtBuscarMotivo = new javax.swing.JTextField();
        txtBuscarId = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        listaResultados = new javax.swing.JList<>();

        txtBuscarMotivo.setToolTipText("Escreva aqui");

        txtBuscarId.setText("Escreva aqui");
        txtBuscarId.setToolTipText("Escreva aqui");

        listaResultados.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(listaResultados);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtBuscarId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtBuscarMotivo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 112, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(58, 58, 58))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addComponent(txtBuscarMotivo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(35, 35, 35)
                        .addComponent(txtBuscarId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(63, 63, 63)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(91, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JList<String> listaResultados;
    private javax.swing.JTextField txtBuscarId;
    private javax.swing.JTextField txtBuscarMotivo;
    // End of variables declaration//GEN-END:variables
}
